"""Type stubs for pyscivex — the complete data science toolkit, powered by Rust."""

from __future__ import annotations

from typing import Any, Callable, Iterator, Sequence

__version__: str

# ===========================================================================
# Core — Tensor
# ===========================================================================

class Tensor:
    def __init__(self, data: Any, shape: list[int] | None = None) -> None: ...
    @staticmethod
    def zeros(shape: list[int]) -> Tensor: ...
    @staticmethod
    def ones(shape: list[int]) -> Tensor: ...
    @staticmethod
    def full(shape: list[int], value: float) -> Tensor: ...
    @staticmethod
    def eye(n: int) -> Tensor: ...
    @staticmethod
    def arange(n: int) -> Tensor: ...
    @staticmethod
    def linspace(start: float, end: float, n: int) -> Tensor: ...
    @staticmethod
    def scalar(value: float) -> Tensor: ...
    @staticmethod
    def concat(tensors: list[Tensor], axis: int) -> Tensor: ...
    @staticmethod
    def stack(tensors: list[Tensor], axis: int) -> Tensor: ...

    # Shape & accessors
    def shape(self) -> list[int]: ...
    def strides(self) -> list[int]: ...
    def ndim(self) -> int: ...
    def numel(self) -> int: ...
    def is_empty(self) -> bool: ...
    def to_list(self) -> list[float]: ...
    def tolist(self) -> Any: ...

    # Indexing
    def get(self, index: list[int]) -> float: ...
    def set(self, index: list[int], value: float) -> None: ...
    def select(self, axis: int, index: int) -> Tensor: ...
    def index_select(self, axis: int, indices: list[int]) -> Tensor: ...
    def masked_select(self, mask: list[bool]) -> Tensor: ...
    def slice(self, ranges: list[list[int]]) -> Tensor: ...

    # Operators
    def __add__(self, other: Tensor | float) -> Tensor: ...
    def __radd__(self, other: Tensor | float) -> Tensor: ...
    def __sub__(self, other: Tensor | float) -> Tensor: ...
    def __rsub__(self, other: Tensor | float) -> Tensor: ...
    def __mul__(self, other: Tensor | float) -> Tensor: ...
    def __rmul__(self, other: Tensor | float) -> Tensor: ...
    def __truediv__(self, other: Tensor | float) -> Tensor: ...
    def __rtruediv__(self, other: Tensor | float) -> Tensor: ...
    def __matmul__(self, other: Tensor) -> Tensor: ...
    def __neg__(self) -> Tensor: ...
    def __pow__(self, exp: float) -> Tensor: ...
    def __bool__(self) -> bool: ...
    def __float__(self) -> float: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __getitem__(self, key: int | list[int]) -> Tensor | float | Any: ...
    def __setitem__(self, key: list[int], value: float) -> None: ...
    def __iter__(self) -> Iterator[Tensor | float]: ...

    # Element-wise math
    def abs(self) -> Tensor: ...
    def sqrt(self) -> Tensor: ...
    def sin(self) -> Tensor: ...
    def cos(self) -> Tensor: ...
    def tan(self) -> Tensor: ...
    def exp(self) -> Tensor: ...
    def ln(self) -> Tensor: ...
    def log2(self) -> Tensor: ...
    def log10(self) -> Tensor: ...
    def floor(self) -> Tensor: ...
    def ceil(self) -> Tensor: ...
    def round(self) -> Tensor: ...
    def powf(self, exponent: float) -> Tensor: ...
    def powi(self, n: int) -> Tensor: ...
    def clamp(self, min: float, max: float) -> Tensor: ...

    # Reductions
    def sum(self) -> float: ...
    def mean(self) -> float: ...
    def product(self) -> float: ...
    def min(self) -> float: ...
    def max(self) -> float: ...
    def sum_axis(self, axis: int) -> Tensor: ...

    # Shape manipulation
    def reshape(self, shape: list[int]) -> Tensor: ...
    def flatten(self) -> Tensor: ...
    def transpose(self) -> Tensor: ...
    def permute(self, axes: list[int]) -> Tensor: ...
    def unsqueeze(self, axis: int) -> Tensor: ...
    def squeeze(self) -> Tensor: ...

    # Sorting
    def sort(self) -> Tensor: ...
    def argsort(self) -> list[int]: ...
    def sort_axis(self, axis: int) -> Tensor: ...

    # Linear algebra
    def dot(self, other: Tensor) -> float: ...
    def norm(self) -> float: ...
    def det(self) -> float: ...
    def inv(self) -> Tensor: ...
    def solve(self, b: Tensor) -> Tensor: ...
    def lstsq(self, b: Tensor) -> Tensor: ...
    def matvec(self, x: Tensor) -> Tensor: ...

    # Functional
    def apply(self, func: Callable[[float], float]) -> Tensor: ...


# ===========================================================================
# DataFrame
# ===========================================================================

class DataFrame:
    def __init__(self, data: dict[str, list[Any]] | None = None) -> None: ...
    def add_column(self, name: str, data: list[float]) -> None: ...
    def add_string_column(self, name: str, data: list[str]) -> None: ...
    def add_int_column(self, name: str, data: list[int]) -> None: ...
    def nrows(self) -> int: ...
    def ncols(self) -> int: ...
    def shape(self) -> tuple[int, int]: ...
    def column_names(self) -> list[str]: ...
    def dtypes(self) -> list[str]: ...
    def is_empty(self) -> bool: ...
    def column(self, name: str) -> list[float]: ...
    def column_str(self, name: str) -> list[str]: ...
    def select(self, columns: list[str]) -> DataFrame: ...
    def drop_columns(self, columns: list[str]) -> DataFrame: ...
    def head(self, n: int) -> DataFrame: ...
    def tail(self, n: int) -> DataFrame: ...
    def slice(self, offset: int, length: int) -> DataFrame: ...
    def filter(self, mask: list[bool]) -> DataFrame: ...
    def sort_values(self, by: str, ascending: bool = True) -> DataFrame: ...
    def groupby(self, by: list[str]) -> GroupBy: ...
    def join(self, other: DataFrame, on: list[str], how: str = "inner") -> DataFrame: ...
    def pivot(self, index: list[str], columns: str, values: str, agg_func: str) -> DataFrame: ...
    def drop_nulls(self) -> DataFrame: ...
    def drop_nulls_subset(self, columns: list[str]) -> DataFrame: ...
    def sql(self, query: str) -> DataFrame: ...
    def to_tensor(self) -> Tensor: ...
    def describe(self) -> str: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
    def __getitem__(self, key: str | list[str]) -> list[Any] | DataFrame: ...


class GroupBy:
    def sum(self) -> DataFrame: ...
    def mean(self) -> DataFrame: ...
    def min(self) -> DataFrame: ...
    def max(self) -> DataFrame: ...
    def count(self) -> DataFrame: ...
    def first(self) -> DataFrame: ...
    def last(self) -> DataFrame: ...


# ===========================================================================
# Top-level stats functions
# ===========================================================================

def mean(data: list[float]) -> float: ...
def variance(data: list[float]) -> float: ...
def std_dev(data: list[float]) -> float: ...
def median(data: list[float]) -> float: ...
def pearson(x: list[float], y: list[float]) -> float: ...


# ===========================================================================
# Top-level ML classes
# ===========================================================================

class LinearRegression:
    def __init__(self) -> None: ...
    def fit(self, x: Tensor, y: Tensor) -> None: ...
    def predict(self, x: Tensor) -> Tensor: ...
    def weights(self) -> list[float] | None: ...
    def bias(self) -> float | None: ...


class KMeans:
    def __init__(self, n_clusters: int, max_iter: int = 100, n_init: int = 3, seed: int = 42) -> None: ...
    def fit(self, x: Tensor, y: Tensor) -> None: ...
    def predict(self, x: Tensor) -> Tensor: ...
    def inertia(self) -> float | None: ...
    def centroids(self) -> Tensor | None: ...


# ===========================================================================
# Visualization
# ===========================================================================

class Figure:
    def __init__(self, width: float = 800.0, height: float = 600.0) -> None: ...
    def line_plot(self, x: list[float], y: list[float], label: str | None = None, color: str | None = None, width: float | None = None) -> None: ...
    def scatter_plot(self, x: list[float], y: list[float], label: str | None = None, color: str | None = None, size: float | None = None) -> None: ...
    def bar_plot(self, categories: list[str], values: list[float], label: str | None = None, color: str | None = None) -> None: ...
    def histogram(self, data: list[float], bins: int = 20, label: str | None = None, color: str | None = None) -> None: ...
    def boxplot(self, datasets: list[list[float]], labels: list[str] | None = None) -> None: ...
    def violin_plot(self, datasets: list[list[float]]) -> None: ...
    def heatmap(self, data: list[list[float]], x_labels: list[str] | None = None, y_labels: list[str] | None = None, show_values: bool = False) -> None: ...
    def pie_chart(self, values: list[float], labels: list[str] | None = None) -> None: ...
    def area_plot(self, x: list[float], y: list[float], label: str | None = None, color: str | None = None) -> None: ...
    def error_bar_plot(self, x: list[float], y: list[float], y_err_low: list[float], y_err_high: list[float], label: str | None = None) -> None: ...
    def contour_plot(self, data: list[list[float]], n_levels: int = 10) -> None: ...
    def polar_plot(self, categories: list[str], values: list[float], label: str | None = None) -> None: ...
    def regression_plot(self, x: list[float], y: list[float], show_ci: bool = True) -> None: ...
    def residual_plot(self, x: list[float], y: list[float]) -> None: ...
    def qq_plot(self, data: list[float]) -> None: ...
    def correlation_heatmap(self, matrix: list[list[float]], labels: list[str] | None = None, show_values: bool = True) -> None: ...
    def confidence_band(self, x: list[float], y_lower: list[float], y_upper: list[float], label: str | None = None) -> None: ...
    def title(self, t: str) -> None: ...
    def x_label(self, l: str) -> None: ...
    def y_label(self, l: str) -> None: ...
    def grid(self, on: bool) -> None: ...
    def theme(self, name: str) -> None: ...
    def to_svg(self) -> str: ...
    def save_svg(self, path: str) -> None: ...
    def to_terminal(self) -> str: ...
    def _repr_svg_(self) -> str: ...


# ===========================================================================
# Submodule declarations
# ===========================================================================

class linalg:
    class LU:
        @staticmethod
        def decompose(a: Tensor) -> linalg.LU: ...
        def l(self) -> Tensor: ...
        def u(self) -> Tensor: ...
        def p(self) -> Tensor: ...
        def det(self) -> float: ...
        def solve(self, b: Tensor) -> Tensor: ...
        def inverse(self) -> Tensor: ...

    class QR:
        @staticmethod
        def decompose(a: Tensor) -> linalg.QR: ...
        def q(self) -> Tensor: ...
        def r(self) -> Tensor: ...
        def is_full_rank(self) -> bool: ...
        def solve(self, b: Tensor) -> Tensor: ...

    class SVD:
        @staticmethod
        def decompose(a: Tensor) -> linalg.SVD: ...
        def singular_values(self) -> list[float]: ...
        def u(self) -> Tensor: ...
        def vt(self) -> Tensor: ...
        def s(self) -> Tensor: ...
        def rank(self, tol: float) -> int: ...
        def condition_number(self) -> float: ...

    class Eig:
        @staticmethod
        def decompose_symmetric(a: Tensor) -> linalg.Eig: ...
        def eigenvalues(self) -> list[float]: ...
        def eigenvectors(self) -> Tensor: ...

    class Cholesky:
        @staticmethod
        def decompose(a: Tensor) -> linalg.Cholesky: ...
        def l(self) -> Tensor: ...
        def solve(self, b: Tensor) -> Tensor: ...
        def inverse(self) -> Tensor: ...
        def log_det(self) -> float: ...

    @staticmethod
    def solve(a: Tensor, b: Tensor) -> Tensor: ...
    @staticmethod
    def inv(a: Tensor) -> Tensor: ...
    @staticmethod
    def det(a: Tensor) -> float: ...
    @staticmethod
    def norm(x: Tensor) -> float: ...
    @staticmethod
    def lstsq(a: Tensor, b: Tensor) -> Tensor: ...


class fft:
    @staticmethod
    def fft_1d(input: Tensor) -> Tensor: ...
    @staticmethod
    def ifft_1d(input: Tensor) -> Tensor: ...
    @staticmethod
    def rfft(input: Tensor) -> Tensor: ...
    @staticmethod
    def irfft(input: Tensor, n: int) -> Tensor: ...
    @staticmethod
    def fft2(input: Tensor) -> Tensor: ...
    @staticmethod
    def ifft2(input: Tensor) -> Tensor: ...


class random:
    class Rng:
        def __init__(self, seed: int) -> None: ...
        def seed(self, seed: int) -> None: ...
        def next_f64(self) -> float: ...
        def next_normal_f64(self) -> float: ...
        def next_u64(self) -> int: ...
        def uniform(self, shape: list[int]) -> Tensor: ...
        def uniform_range(self, shape: list[int], low: float, high: float) -> Tensor: ...
        def normal(self, shape: list[int], mean: float, std_dev: float) -> Tensor: ...
        def standard_normal(self, shape: list[int]) -> Tensor: ...
        def randint(self, shape: list[int], low: int, high: int) -> Tensor: ...

    class Binomial:
        def __init__(self, n: int, p: float) -> None: ...
        def sample(self, seed: int) -> int: ...
        def sample_n(self, count: int, seed: int) -> list[int]: ...


class io:
    @staticmethod
    def read_csv(path: str, delimiter: str | None = None, has_header: bool | None = None, skip_rows: int | None = None, max_rows: int | None = None) -> DataFrame: ...
    @staticmethod
    def write_csv(df: DataFrame, path: str, delimiter: str | None = None, write_header: bool | None = None) -> None: ...
    @staticmethod
    def read_json(path: str, orient: str | None = None) -> DataFrame: ...
    @staticmethod
    def write_json(df: DataFrame, path: str, orient: str | None = None, pretty: bool | None = None) -> None: ...


class stats:
    # Descriptive
    @staticmethod
    def quantile(data: list[float], q: float) -> float: ...
    @staticmethod
    def skewness(data: list[float]) -> float: ...
    @staticmethod
    def kurtosis(data: list[float]) -> float: ...
    @staticmethod
    def variance_with_ddof(data: list[float], ddof: int) -> float: ...
    @staticmethod
    def std_dev_with_ddof(data: list[float], ddof: int) -> float: ...
    @staticmethod
    def describe(data: list[float]) -> dict[str, float]: ...

    # Correlation
    @staticmethod
    def corr_matrix(data: Tensor, method: str) -> Tensor: ...
    @staticmethod
    def spearman(x: list[float], y: list[float]) -> float: ...
    @staticmethod
    def kendall(x: list[float], y: list[float]) -> float: ...

    # Regression
    @staticmethod
    def ols(x: Tensor, y: list[float]) -> dict[str, Any]: ...
    @staticmethod
    def glm(x: Tensor, y: list[float], family: str, link: str | None = None) -> dict[str, Any]: ...

    # Confidence intervals
    @staticmethod
    def ci_mean(data: list[float], confidence: float) -> dict[str, float]: ...
    @staticmethod
    def ci_proportion(successes: int, total: int, confidence: float) -> dict[str, float]: ...

    # Effect size
    @staticmethod
    def cohens_d(group1: list[float], group2: list[float]) -> float: ...
    @staticmethod
    def hedges_g(group1: list[float], group2: list[float]) -> float: ...
    @staticmethod
    def glass_delta(treatment: list[float], control: list[float]) -> float: ...
    @staticmethod
    def eta_squared(groups: list[list[float]]) -> float: ...
    @staticmethod
    def omega_squared(groups: list[list[float]]) -> float: ...

    # Multiple testing corrections
    @staticmethod
    def bonferroni(p_values: list[float]) -> list[float]: ...
    @staticmethod
    def benjamini_hochberg(p_values: list[float]) -> list[float]: ...

    # Hypothesis tests
    @staticmethod
    def ttest_1samp(data: list[float], mu: float) -> dict[str, float]: ...
    @staticmethod
    def ttest_ind(x: list[float], y: list[float]) -> dict[str, float]: ...
    @staticmethod
    def chi2_test(observed: list[float], expected: list[float]) -> dict[str, float]: ...
    @staticmethod
    def ks_2samp(x: list[float], y: list[float]) -> dict[str, float]: ...
    @staticmethod
    def anova_oneway(groups: list[list[float]]) -> dict[str, float]: ...
    @staticmethod
    def mann_whitney_u(x: list[float], y: list[float]) -> dict[str, float]: ...

    # Distributions
    class Normal:
        def __init__(self, mu: float, sigma: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Uniform:
        def __init__(self, a: float, b: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Exponential:
        def __init__(self, lambda_: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class StudentT:
        def __init__(self, df: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Beta:
        def __init__(self, alpha: float, beta: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Gamma:
        def __init__(self, alpha: float, beta: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Poisson:
        def __init__(self, lambda_: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class ChiSquared:
        def __init__(self, df: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Bernoulli:
        def __init__(self, p: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Cauchy:
        def __init__(self, x0: float, gamma: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class LogNormal:
        def __init__(self, mu: float, sigma: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Weibull:
        def __init__(self, k: float, lambda_: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...

    class Laplace:
        def __init__(self, mu: float, b: float) -> None: ...
        def pdf(self, x: float) -> float: ...
        def cdf(self, x: float) -> float: ...
        def ppf(self, p: float) -> float: ...
        def mean(self) -> float: ...
        def variance(self) -> float: ...
        def sample(self, seed: int) -> float: ...
        def sample_n(self, n: int, seed: int) -> list[float]: ...


class ml:
    # Linear models
    class LinearRegression:
        def __init__(self) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def weights(self) -> list[float] | None: ...
        def bias(self) -> float | None: ...

    class Ridge:
        def __init__(self, alpha: float) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class LogisticRegression:
        def __init__(self, learning_rate: float, max_iter: int, tol: float) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def predict_proba(self, x: Tensor) -> Tensor: ...

    # Trees
    class DecisionTreeClassifier:
        def __init__(self, max_depth: int | None = None, min_samples_split: int = 0) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class DecisionTreeRegressor:
        def __init__(self, max_depth: int | None = None, min_samples_split: int = 0) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    # Ensemble
    class RandomForestClassifier:
        def __init__(self, n_trees: int, max_depth: int | None, max_features: int | None, seed: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class RandomForestRegressor:
        def __init__(self, n_trees: int, max_depth: int | None, max_features: int | None, seed: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class GradientBoostingRegressor:
        def __init__(self, n_estimators: int, learning_rate: float, max_depth: int | None = None, loss: str = "mse") -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class GradientBoostingClassifier:
        def __init__(self, n_estimators: int, learning_rate: float, max_depth: int | None) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    # SVM
    class SVC:
        def __init__(self, kernel: str = "rbf", c: float = 1.0, gamma: float = 1.0, degree: int = 3, coef0: float = 0.0) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class SVR:
        def __init__(self, kernel: str = "rbf", c: float = 1.0, epsilon: float = 0.1, gamma: float = 1.0, degree: int = 3, coef0: float = 0.0) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    # Neighbors
    class KNNClassifier:
        def __init__(self, k: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    class KNNRegressor:
        def __init__(self, k: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...

    # Naive Bayes
    class GaussianNB:
        def __init__(self) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def predict_proba(self, x: Tensor) -> Tensor: ...

    # Clustering
    class KMeans:
        def __init__(self, n_clusters: int, max_iter: int = 100, n_init: int = 3, seed: int = 42) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def inertia(self) -> float | None: ...
        def centroids(self) -> Tensor | None: ...

    class DBSCAN:
        def __init__(self, eps: float = 0.5, min_samples: int = 5) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def labels(self) -> list[int]: ...
        def fit_predict(self, x: Tensor) -> Tensor: ...

    class AgglomerativeClustering:
        def __init__(self, n_clusters: int, linkage: str = "ward") -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def labels(self) -> list[int]: ...
        def fit_predict(self, x: Tensor) -> list[int]: ...

    # Decomposition
    class PCA:
        def __init__(self, n_components: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def transform(self, x: Tensor) -> Tensor: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...
        def explained_variance(self) -> list[float] | None: ...
        def explained_variance_ratio(self) -> list[float] | None: ...
        def components(self) -> list[float] | None: ...

    class TruncatedSVD:
        def __init__(self, n_components: int) -> None: ...
        def fit(self, x: Tensor, y: Tensor) -> None: ...
        def predict(self, x: Tensor) -> Tensor: ...
        def transform(self, x: Tensor) -> Tensor: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...
        def explained_variance(self) -> list[float] | None: ...
        def explained_variance_ratio(self) -> list[float] | None: ...

    class TSNE:
        def __init__(self, n_components: int = 2, perplexity: float = 30.0) -> None: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...

    # Preprocessing
    class StandardScaler:
        def __init__(self) -> None: ...
        def fit(self, x: Tensor) -> None: ...
        def transform(self, x: Tensor) -> Tensor: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...

    class MinMaxScaler:
        def __init__(self) -> None: ...
        def fit(self, x: Tensor) -> None: ...
        def transform(self, x: Tensor) -> Tensor: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...

    class OneHotEncoder:
        def __init__(self) -> None: ...
        def fit(self, x: Tensor) -> None: ...
        def transform(self, x: Tensor) -> Tensor: ...
        def fit_transform(self, x: Tensor) -> Tensor: ...

    class LabelEncoder:
        def __init__(self) -> None: ...
        def fit(self, y: list[float]) -> None: ...
        def transform(self, y: list[float]) -> list[int]: ...
        def inverse_transform(self, indices: list[int]) -> list[float]: ...
        def n_classes(self) -> int | None: ...

    # Metrics
    @staticmethod
    def accuracy(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def precision(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def recall(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def f1_score(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def confusion_matrix(y_true: list[float], y_pred: list[float], n_classes: int) -> list[list[int]]: ...
    @staticmethod
    def mse(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def rmse(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def mae(y_true: list[float], y_pred: list[float]) -> float: ...
    @staticmethod
    def r2_score(y_true: list[float], y_pred: list[float]) -> float: ...

    # Model selection
    @staticmethod
    def train_test_split(x: Tensor, y: Tensor, test_ratio: float = 0.2, seed: int = 42) -> dict[str, Tensor]: ...


class optim:
    # Root finding
    @staticmethod
    def bisection(f: Callable[[float], float], a: float, b: float, xtol: float = 1e-12, ftol: float = 1e-12, max_iter: int = 100) -> dict[str, Any]: ...
    @staticmethod
    def brentq(f: Callable[[float], float], a: float, b: float, xtol: float = 1e-12, ftol: float = 1e-12, max_iter: int = 100) -> dict[str, Any]: ...
    @staticmethod
    def newton(f: Callable[[float], float], fprime: Callable[[float], float], x0: float, xtol: float = 1e-12, ftol: float = 1e-12, max_iter: int = 100) -> dict[str, Any]: ...

    # Integration
    @staticmethod
    def trapezoid(f: Callable[[float], float], a: float, b: float, n: int = 1000) -> dict[str, Any]: ...
    @staticmethod
    def simpson(f: Callable[[float], float], a: float, b: float, n: int = 1000) -> dict[str, Any]: ...
    @staticmethod
    def quad(f: Callable[[float], float], a: float, b: float, abs_tol: float = 1e-10, rel_tol: float = 1e-10, max_subdivisions: int = 50) -> dict[str, Any]: ...

    # Interpolation
    @staticmethod
    def interp1d(xs: list[float], ys: list[float], query: list[float], method: str = "linear") -> list[float]: ...

    class CubicSpline:
        def __init__(self, xs: list[float], ys: list[float], boundary: str = "natural") -> None: ...
        def eval(self, x: float) -> float: ...
        def eval_many(self, xs: list[float]) -> list[float]: ...

    # Minimization
    @staticmethod
    def minimize(f: Callable[[Tensor], float], x0: Tensor, method: str = "bfgs", jac: Callable[[Tensor], Tensor] | None = None, gtol: float = 1e-5, xtol: float = 1e-9, ftol: float = 1e-9, max_iter: int = 1000, learning_rate: float = 0.01) -> dict[str, Any]: ...
    @staticmethod
    def golden_section(f: Callable[[float], float], a: float, b: float, xtol: float = 1e-12, max_iter: int = 500) -> dict[str, Any]: ...
    @staticmethod
    def brent_min(f: Callable[[float], float], a: float, b: float, xtol: float = 1e-12, max_iter: int = 500) -> dict[str, Any]: ...

    # ODE
    @staticmethod
    def solve_ivp(f: Callable[[float, list[float]], list[float]], t_span: tuple[float, float], y0: list[float], method: str = "rk45", atol: float = 1e-6, rtol: float = 1e-3, max_steps: int = 10000) -> dict[str, Any]: ...

    # Curve fitting
    @staticmethod
    def curve_fit(model: Callable[[float, list[float]], float], x_data: list[float], y_data: list[float], p0: list[float], max_iter: int = 1000, tol: float = 1e-8) -> dict[str, Any]: ...

    # Linear programming
    @staticmethod
    def linprog(c: list[float], a_ub: list[list[float]], b_ub: list[float]) -> dict[str, Any]: ...

    # PDE
    @staticmethod
    def heat_equation_1d(initial: Callable[[float], float], x_range: tuple[float, float], n_x: int, t_final: float, n_t: int, alpha: float = 1.0, left_bc: float = 0.0, right_bc: float = 0.0) -> dict[str, Any]: ...


class nn:
    class Variable:
        def __init__(self, data: Any, requires_grad: bool = False) -> None: ...
        def data(self) -> Tensor: ...
        def shape(self) -> list[int]: ...
        def grad(self) -> Tensor | None: ...
        def requires_grad(self) -> bool: ...
        def backward(self) -> None: ...
        def zero_grad(self) -> None: ...
        def detach(self) -> nn.Variable: ...

    @staticmethod
    def tensor(data: Any, requires_grad: bool = False) -> nn.Variable: ...

    # Layers
    class Linear:
        def __init__(self, in_features: int, out_features: int, bias: bool | None = None, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class Conv1d:
        def __init__(self, in_channels: int, out_channels: int, kernel_size: int, bias: bool | None = None, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class Conv2d:
        def __init__(self, in_channels: int, out_channels: int, kernel_h: int, kernel_w: int, bias: bool | None = None, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class BatchNorm1d:
        def __init__(self, num_features: int) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class BatchNorm2d:
        def __init__(self, num_channels: int) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class Dropout:
        def __init__(self, p: float, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class Embedding:
        def __init__(self, num_embeddings: int, dim: int, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class LayerNorm:
        def __init__(self, num_features: int) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class LSTM:
        def __init__(self, input_size: int, hidden_size: int, seq_len: int, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class GRU:
        def __init__(self, input_size: int, hidden_size: int, seq_len: int, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class MultiHeadAttention:
        def __init__(self, d_model: int, num_heads: int, seq_len: int, seed: int | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...

    class ReLU:
        def __init__(self) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...

    class Sigmoid:
        def __init__(self) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...

    class Tanh:
        def __init__(self) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...

    class Flatten:
        def __init__(self) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...

    class Sequential:
        def __init__(self, layers: list[Any] | None = None) -> None: ...
        def forward(self, x: nn.Variable) -> nn.Variable: ...
        def parameters(self) -> list[nn.Variable]: ...
        def train(self) -> None: ...
        def eval(self) -> None: ...
        def __len__(self) -> int: ...

    # Functional activations
    @staticmethod
    def relu(x: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def sigmoid(x: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def tanh_act(x: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def softmax(x: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def log_softmax(x: nn.Variable) -> nn.Variable: ...

    # Loss functions
    @staticmethod
    def mse_loss(pred: nn.Variable, target: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def cross_entropy_loss(logits: nn.Variable, targets: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def bce_loss(pred: nn.Variable, target: nn.Variable) -> nn.Variable: ...
    @staticmethod
    def huber_loss(pred: nn.Variable, target: nn.Variable, delta: float = 1.0) -> nn.Variable: ...
    @staticmethod
    def focal_loss(logits: nn.Variable, targets: nn.Variable, gamma: float = 2.0, alpha: float = 0.25) -> nn.Variable: ...

    # Optimizers
    class SGD:
        def __init__(self, params: list[nn.Variable], lr: float, momentum: float = 0.0, weight_decay: float = 0.0) -> None: ...
        def step(self) -> None: ...
        def zero_grad(self) -> None: ...

    class Adam:
        def __init__(self, params: list[nn.Variable], lr: float = 0.001) -> None: ...
        def step(self) -> None: ...
        def zero_grad(self) -> None: ...

    class AdamW:
        def __init__(self, params: list[nn.Variable], lr: float = 0.001, weight_decay: float = 0.01) -> None: ...
        def step(self) -> None: ...
        def zero_grad(self) -> None: ...

    class RMSprop:
        def __init__(self, params: list[nn.Variable], lr: float = 0.01) -> None: ...
        def step(self) -> None: ...
        def zero_grad(self) -> None: ...

    # Schedulers
    class StepLR:
        def __init__(self, base_lr: float, step_size: int, gamma: float) -> None: ...
        def get_lr(self) -> float: ...
        def step(self) -> None: ...

    class CosineAnnealingLR:
        def __init__(self, base_lr: float, t_max: int, eta_min: float = 0.0) -> None: ...
        def get_lr(self) -> float: ...
        def step(self) -> None: ...

    class ReduceLROnPlateau:
        def __init__(self, initial_lr: float, factor: float = 0.1, patience: int = 10, min_lr: float = 0.0) -> None: ...
        def step(self, metric: float) -> float: ...
        def get_lr(self) -> float: ...

    # Data
    class TensorDataset:
        def __init__(self, x: Tensor, y: Tensor) -> None: ...
        def __len__(self) -> int: ...
        def get(self, index: int) -> tuple[Tensor, Tensor]: ...

    # Persistence
    @staticmethod
    def save_weights(path: str, params: list[nn.Variable]) -> None: ...
    @staticmethod
    def load_weights(path: str) -> list[Tensor]: ...


class signal:
    # Windows
    @staticmethod
    def hann(n: int) -> Tensor: ...
    @staticmethod
    def hamming(n: int) -> Tensor: ...
    @staticmethod
    def blackman(n: int) -> Tensor: ...
    @staticmethod
    def bartlett(n: int) -> Tensor: ...

    # Filters
    @staticmethod
    def lfilter(b: list[float], a: list[float], x: list[float]) -> Tensor: ...
    @staticmethod
    def filtfilt(b: list[float], a: list[float], x: list[float]) -> Tensor: ...
    @staticmethod
    def firwin_lowpass(cutoff: float, num_taps: int) -> Tensor: ...
    @staticmethod
    def firwin_highpass(cutoff: float, num_taps: int) -> Tensor: ...
    @staticmethod
    def firwin_bandpass(low: float, high: float, num_taps: int) -> Tensor: ...

    # Spectral
    @staticmethod
    def stft(x: list[float], window_size: int, hop_size: int, window: list[float] | None = None) -> Tensor: ...
    @staticmethod
    def istft(stft_result: Tensor, window_size: int, hop_size: int, window: list[float] | None = None) -> Tensor: ...
    @staticmethod
    def spectrogram(x: list[float], window_size: int, hop_size: int) -> Tensor: ...
    @staticmethod
    def periodogram(x: list[float]) -> tuple[Tensor, Tensor]: ...
    @staticmethod
    def welch(x: list[float], segment_size: int, overlap: int) -> tuple[Tensor, Tensor]: ...

    # Wavelets
    @staticmethod
    def dwt(x: list[float], wavelet: str = "haar") -> tuple[Tensor, Tensor]: ...
    @staticmethod
    def idwt(approx: list[float], detail: list[float], wavelet: str = "haar") -> Tensor: ...

    # Audio features
    @staticmethod
    def hz_to_mel(hz: float) -> float: ...
    @staticmethod
    def mel_to_hz(mel: float) -> float: ...
    @staticmethod
    def mel_spectrogram(x: list[float], sample_rate: float, n_fft: int, hop_size: int, n_mels: int) -> Tensor: ...
    @staticmethod
    def mfcc(x: list[float], sample_rate: float, n_mfcc: int, n_mels: int, n_fft: int, hop_size: int) -> Tensor: ...
    @staticmethod
    def chroma_stft(x: list[float], sample_rate: float, n_fft: int, hop_size: int, n_chroma: int = 12) -> Tensor: ...
    @staticmethod
    def pitch_yin(x: list[float], sample_rate: float, frame_size: int, hop_size: int, threshold: float = 0.15) -> list[float]: ...

    # Peaks
    @staticmethod
    def find_peaks(x: list[float], min_height: float | None = None, min_distance: int | None = None) -> list[int]: ...
    @staticmethod
    def peak_prominences(x: list[float], peaks: list[int]) -> list[float]: ...

    # Resampling
    @staticmethod
    def resample(x: list[float], num_samples: int) -> Tensor: ...
    @staticmethod
    def decimate(x: list[float], factor: int) -> Tensor: ...

    # Convolution
    @staticmethod
    def convolve(a: list[float], b: list[float], mode: str = "full") -> Tensor: ...
    @staticmethod
    def correlate(a: list[float], b: list[float], mode: str = "full") -> Tensor: ...

    # Audio I/O
    class AudioData:
        @property
        def samples(self) -> list[float]: ...
        @property
        def channels(self) -> int: ...
        @property
        def sample_rate(self) -> int: ...
        @property
        def bits_per_sample(self) -> int: ...
        def num_frames(self) -> int: ...
        def channel(self, ch: int) -> list[float]: ...
        def to_mono(self) -> list[float]: ...

    @staticmethod
    def read_wav(path: str) -> signal.AudioData: ...
    @staticmethod
    def write_wav(path: str, samples: list[float], channels: int = 1, sample_rate: int = 44100) -> None: ...

    # Rhythm
    @staticmethod
    def onset_strength(signal: list[float], sample_rate: float, frame_size: int, hop_size: int) -> dict[str, Any]: ...
    @staticmethod
    def detect_onsets(signal: list[float], sample_rate: float, frame_size: int, hop_size: int) -> dict[str, Any]: ...
    @staticmethod
    def beat_track(signal: list[float], sample_rate: float, frame_size: int, hop_size: int) -> dict[str, Any]: ...


class image:
    class Image:
        def __init__(self, data: list[int], width: int, height: int, channels: int = 3) -> None: ...
        @staticmethod
        def zeros(width: int, height: int, channels: int = 3) -> image.Image: ...
        @staticmethod
        def open(path: str) -> image.Image: ...
        def save(self, path: str) -> None: ...
        @property
        def width(self) -> int: ...
        @property
        def height(self) -> int: ...
        @property
        def channels(self) -> int: ...
        @property
        def format(self) -> str: ...
        def dimensions(self) -> tuple[int, int]: ...
        def shape(self) -> list[int]: ...
        def to_list(self) -> list[int]: ...
        def to_tensor(self) -> Tensor: ...
        def get_pixel(self, row: int, col: int) -> bytes: ...
        def set_pixel(self, row: int, col: int, values: list[int]) -> None: ...
        def to_grayscale(self) -> image.Image: ...
        def to_rgb(self) -> image.Image: ...
        def invert(self) -> image.Image: ...
        def resize(self, new_width: int, new_height: int, method: str = "nearest") -> image.Image: ...
        def crop(self, x: int, y: int, width: int, height: int) -> image.Image: ...
        def flip_horizontal(self) -> image.Image: ...
        def flip_vertical(self) -> image.Image: ...
        def rotate90(self) -> image.Image: ...
        def rotate180(self) -> image.Image: ...
        def rotate270(self) -> image.Image: ...
        def pad(self, top: int, bottom: int, left: int, right: int, value: int = 0) -> image.Image: ...
        def erode(self, kind: str = "rect", size: int = 3) -> image.Image: ...
        def dilate(self, kind: str = "rect", size: int = 3) -> image.Image: ...
        def opening(self, kind: str = "rect", size: int = 3) -> image.Image: ...
        def closing(self, kind: str = "rect", size: int = 3) -> image.Image: ...
        def draw_line(self, x0: int, y0: int, x1: int, y1: int, color: list[int]) -> None: ...
        def draw_rect(self, x: int, y: int, w: int, h: int, color: list[int]) -> None: ...
        def fill_rect(self, x: int, y: int, w: int, h: int, color: list[int]) -> None: ...
        def draw_circle(self, cx: int, cy: int, radius: int, color: list[int]) -> None: ...
        def histogram(self) -> Tensor: ...
        def equalize(self) -> image.Image: ...
        def connected_components(self, threshold: int) -> tuple[list[int], int]: ...
        def region_growing(self, seeds: list[tuple[int, int]], tolerance: int) -> list[int]: ...

    class AugmentPipeline:
        def __init__(self) -> None: ...
        def random_flip_h(self, prob: float) -> None: ...
        def random_flip_v(self, prob: float) -> None: ...
        def random_brightness(self, delta: float) -> None: ...
        def gaussian_noise(self, sigma: float) -> None: ...
        def random_crop(self, width: int, height: int) -> None: ...
        def color_jitter(self, brightness: float = 0.0, contrast: float = 0.0, saturation: float = 0.0, hue: float = 0.0) -> None: ...
        def random_rotation(self, max_angle: float) -> None: ...
        def cutout(self, width: int, height: int) -> None: ...
        def normalize(self, mean: list[float], std: list[float]) -> None: ...
        def apply(self, img: image.Image, seed: int = 42) -> image.Image: ...

    # Filters & processing
    @staticmethod
    def rgb_to_hsv(img: image.Image) -> image.Image: ...
    @staticmethod
    def hsv_to_rgb(img: image.Image) -> image.Image: ...
    @staticmethod
    def gaussian_blur(img: image.Image, sigma: float) -> image.Image: ...
    @staticmethod
    def box_blur(img: image.Image, radius: int) -> image.Image: ...
    @staticmethod
    def sharpen(img: image.Image) -> image.Image: ...
    @staticmethod
    def sobel(img: image.Image) -> image.Image: ...
    @staticmethod
    def sobel_x(img: image.Image) -> image.Image: ...
    @staticmethod
    def sobel_y(img: image.Image) -> image.Image: ...
    @staticmethod
    def median_filter(img: image.Image, radius: int) -> image.Image: ...
    @staticmethod
    def resize_lanczos(img: image.Image, new_width: int, new_height: int, a: int = 3) -> image.Image: ...
    @staticmethod
    def harris_corners(img: image.Image, k: float = 0.04, threshold: float = 1000000.0, block_size: int = 3) -> list[tuple[int, int, float]]: ...
    @staticmethod
    def fast_corners(img: image.Image, threshold: int = 20, nonmax: bool = True) -> list[tuple[int, int, float]]: ...
    @staticmethod
    def orb_features(img: image.Image, n_features: int = 500, fast_threshold: int = 20) -> list[dict[str, Any]]: ...
    @staticmethod
    def match_features(query: list[list[int]], train: list[list[int]], ratio: float | None = None) -> list[tuple[int, int, int]]: ...
    @staticmethod
    def hough_lines(img: image.Image, rho_resolution: float = 1.0, theta_resolution: float = 0.01745329, threshold: int = 50) -> list[tuple[float, float, int]]: ...
    @staticmethod
    def hough_circles(img: image.Image, min_radius: int, max_radius: int, threshold: int = 50) -> list[tuple[int, int, int, int]]: ...
    @staticmethod
    def find_contours(img: image.Image, threshold: int = 128) -> list[list[tuple[int, int]]]: ...
    @staticmethod
    def contour_area(points: list[tuple[int, int]]) -> float: ...
    @staticmethod
    def contour_perimeter(points: list[tuple[int, int]]) -> float: ...
    @staticmethod
    def lucas_kanade(prev: image.Image, next: image.Image, window_size: int = 5) -> dict[str, Any]: ...
    @staticmethod
    def watershed(img: image.Image, markers: list[int], width: int, height: int) -> list[int]: ...


class nlp:
    @staticmethod
    def word_tokenize(text: str) -> list[str]: ...
    @staticmethod
    def char_tokenize(text: str) -> list[str]: ...
    @staticmethod
    def ngram_tokenize(text: str, n: int) -> list[str]: ...
    @staticmethod
    def whitespace_tokenize(text: str) -> list[str]: ...
    @staticmethod
    def stopwords() -> list[str]: ...
    @staticmethod
    def is_stopword(word: str) -> bool: ...
    @staticmethod
    def remove_stopwords(tokens: list[str]) -> list[str]: ...
    @staticmethod
    def ngrams(tokens: list[str], n: int) -> list[list[str]]: ...
    @staticmethod
    def edit_distance(a: str, b: str) -> int: ...
    @staticmethod
    def normalize(text: str) -> str: ...
    @staticmethod
    def pad_sequences(sequences: list[list[int]], max_len: int, pad_value: int) -> list[list[int]]: ...
    @staticmethod
    def cosine_sim(a: list[float], b: list[float]) -> float: ...
    @staticmethod
    def jaccard(a: list[str], b: list[str]) -> float: ...
    @staticmethod
    def edit_distance_norm(a: str, b: str) -> float: ...

    class WordPieceTokenizer:
        def __init__(self, vocab: list[str]) -> None: ...
        def tokenize(self, text: str) -> list[str]: ...
        def encode(self, text: str) -> list[int]: ...
        def decode(self, ids: list[int]) -> str: ...

    class PorterStemmer:
        def __init__(self) -> None: ...
        def stem(self, word: str) -> str: ...
        def stem_many(self, words: list[str]) -> list[str]: ...

    class CountVectorizer:
        def __init__(self) -> None: ...
        def fit(self, documents: list[str]) -> None: ...
        def transform(self, documents: list[str]) -> Tensor: ...
        def fit_transform(self, documents: list[str]) -> Tensor: ...
        def vocabulary(self) -> dict[str, int]: ...
        def is_fitted(self) -> bool: ...

    class TfidfVectorizer:
        def __init__(self) -> None: ...
        def fit(self, documents: list[str]) -> None: ...
        def transform(self, documents: list[str]) -> Tensor: ...
        def fit_transform(self, documents: list[str]) -> Tensor: ...
        def vocabulary(self) -> dict[str, int]: ...

    class Word2Vec:
        def __init__(self, embedding_dim: int = 50, window_size: int = 5, min_count: int = 1, learning_rate: float = 0.025, epochs: int = 5, negative_samples: int = 5, seed: int = 42, model: str = "skipgram") -> None: ...
        @staticmethod
        def train(corpus: list[list[str]], embedding_dim: int = 50, window_size: int = 5, min_count: int = 1, learning_rate: float = 0.025, epochs: int = 5, negative_samples: int = 5, seed: int = 42, model: str = "skipgram") -> nlp.Word2Vec: ...
        def get(self, word: str) -> list[float] | None: ...
        def most_similar(self, word: str, top_k: int) -> list[tuple[str, float]]: ...
        def analogy(self, a: str, b: str, c: str, top_k: int) -> list[tuple[str, float]]: ...
        def vocab_size(self) -> int: ...
        def embedding_dim(self) -> int: ...

    class WordEmbeddings:
        def __init__(self, pairs: list[tuple[str, list[float]]]) -> None: ...
        def get(self, word: str) -> list[float] | None: ...
        def most_similar(self, word: str, top_k: int) -> list[tuple[str, float]]: ...
        def analogy(self, a: str, b: str, c: str, top_k: int) -> list[tuple[str, float]]: ...
        def similarity(self, a: str, b: str) -> float: ...
        def vocab_size(self) -> int: ...
        def embedding_dim(self) -> int: ...

    class SentimentAnalyzer:
        def __init__(self) -> None: ...
        def analyze(self, text: str) -> dict[str, float]: ...

    class HmmPosTagger:
        def __init__(self) -> None: ...
        def tag(self, text: str) -> list[tuple[str, str]]: ...
        def tag_tokens(self, tokens: list[str]) -> list[tuple[str, str]]: ...

    class RuleBasedNer:
        def __init__(self) -> None: ...
        def add_entity(self, entity_type: str, name: str) -> None: ...
        def recognize(self, tokens: list[str]) -> list[dict[str, Any]]: ...
        def recognize_text(self, text: str) -> list[dict[str, Any]]: ...

    class LDA:
        def __init__(self, n_topics: int = 10, alpha: float = 0.1, beta: float = 0.01, n_iterations: int = 100, seed: int = 42) -> None: ...
        def fit(self, documents: list[list[str]]) -> None: ...
        def top_words(self, topic: int, n: int) -> list[tuple[str, float]]: ...
        def topic_word_distribution(self, topic: int) -> list[tuple[str, float]]: ...
        def document_topic_distribution(self, doc_idx: int) -> list[float]: ...
        def n_topics(self) -> int: ...


class graph:
    class Graph:
        def __init__(self) -> None: ...
        @staticmethod
        def from_edges(edges: list[tuple[int, int, float]]) -> graph.Graph: ...
        def add_node(self) -> int: ...
        def add_edge(self, u: int, v: int, weight: float) -> None: ...
        def remove_node(self, u: int) -> None: ...
        def remove_edge(self, u: int, v: int) -> None: ...
        @property
        def node_count(self) -> int: ...
        @property
        def edge_count(self) -> int: ...
        def neighbors(self, u: int) -> list[tuple[int, float]]: ...
        def degree(self, u: int) -> int: ...
        def has_edge(self, u: int, v: int) -> bool: ...
        def get_weight(self, u: int, v: int) -> float: ...
        def node_ids(self) -> list[int]: ...
        def edges(self) -> list[tuple[int, int, float]]: ...
        def bfs(self, start: int) -> list[int]: ...
        def dfs(self, start: int) -> list[int]: ...
        def dijkstra(self, source: int) -> tuple[list[float], list[int | None]]: ...
        def bellman_ford(self, source: int) -> tuple[list[float], list[int | None]]: ...
        def floyd_warshall(self) -> list[list[float]]: ...
        def shortest_path(self, source: int, target: int) -> list[int] | None: ...
        def connected_components(self) -> list[list[int]]: ...
        def is_connected(self) -> bool: ...
        def kruskal(self) -> tuple[list[tuple[int, int, float]], float]: ...
        def prim(self) -> tuple[list[tuple[int, int, float]], float]: ...
        def degree_centrality(self) -> list[float]: ...
        def betweenness_centrality(self) -> list[float]: ...
        def label_propagation(self, max_iter: int = 100) -> tuple[list[int], int]: ...

    class DiGraph:
        def __init__(self) -> None: ...
        @staticmethod
        def from_edges(edges: list[tuple[int, int, float]]) -> graph.DiGraph: ...
        def add_node(self) -> int: ...
        def add_edge(self, u: int, v: int, weight: float) -> None: ...
        def remove_node(self, u: int) -> None: ...
        def remove_edge(self, u: int, v: int) -> None: ...
        @property
        def node_count(self) -> int: ...
        @property
        def edge_count(self) -> int: ...
        def neighbors(self, u: int) -> list[tuple[int, float]]: ...
        def in_neighbors(self, u: int) -> list[tuple[int, float]]: ...
        def out_degree(self, u: int) -> int: ...
        def in_degree(self, u: int) -> int: ...
        def has_edge(self, u: int, v: int) -> bool: ...
        def get_weight(self, u: int, v: int) -> float: ...
        def node_ids(self) -> list[int]: ...
        def edges(self) -> list[tuple[int, int, float]]: ...
        def bfs(self, start: int) -> list[int]: ...
        def dfs(self, start: int) -> list[int]: ...
        def topological_sort(self) -> list[int]: ...
        def dijkstra(self, source: int) -> tuple[list[float], list[int | None]]: ...
        def bellman_ford(self, source: int) -> tuple[list[float], list[int | None]]: ...
        def floyd_warshall(self) -> list[list[float]]: ...
        def shortest_path(self, source: int, target: int) -> list[int] | None: ...
        def strongly_connected_components(self) -> list[list[int]]: ...
        def is_strongly_connected(self) -> bool: ...
        def weakly_connected_components(self) -> list[list[int]]: ...
        def in_degree_centrality(self) -> list[float]: ...
        def out_degree_centrality(self) -> list[float]: ...
        def pagerank(self, damping: float = 0.85, max_iter: int = 100, tol: float = 1e-6) -> list[float]: ...
        def max_flow(self, source: int, sink: int) -> tuple[float, list[tuple[int, int, float]]]: ...

    @staticmethod
    def bipartite_matching(left_size: int, right_size: int, edges: list[tuple[int, int]]) -> tuple[list[tuple[int, int]], int]: ...


class sym:
    class Expr:
        def eval(self, vars: dict[str, float]) -> float: ...
        def substitute(self, var: str, replacement: sym.Expr) -> sym.Expr: ...
        def free_variables(self) -> list[str]: ...
        def is_zero(self) -> bool: ...
        def is_one(self) -> bool: ...
        def is_const(self) -> bool: ...
        def as_const(self) -> float | None: ...
        def __add__(self, other: sym.Expr) -> sym.Expr: ...
        def __radd__(self, other: sym.Expr) -> sym.Expr: ...
        def __sub__(self, other: sym.Expr) -> sym.Expr: ...
        def __rsub__(self, other: sym.Expr) -> sym.Expr: ...
        def __mul__(self, other: sym.Expr) -> sym.Expr: ...
        def __rmul__(self, other: sym.Expr) -> sym.Expr: ...
        def __truediv__(self, other: sym.Expr) -> sym.Expr: ...
        def __neg__(self) -> sym.Expr: ...
        def __pow__(self, exp: sym.Expr, modulo: Any = None) -> sym.Expr: ...
        def __repr__(self) -> str: ...
        def __str__(self) -> str: ...

    class Polynomial:
        def __init__(self, coeffs: list[float]) -> None: ...
        def degree(self) -> int: ...
        def coeffs(self) -> list[float]: ...
        def eval(self, x: float) -> float: ...
        def roots(self) -> list[float]: ...
        def add(self, other: sym.Polynomial) -> sym.Polynomial: ...
        def mul(self, other: sym.Polynomial) -> sym.Polynomial: ...
        def to_expr(self, var_name: str = "x") -> sym.Expr: ...
        def __repr__(self) -> str: ...

    @staticmethod
    def var(name: str) -> sym.Expr: ...
    @staticmethod
    def constant(v: float) -> sym.Expr: ...
    @staticmethod
    def sym_pi() -> sym.Expr: ...
    @staticmethod
    def sym_e() -> sym.Expr: ...
    @staticmethod
    def sym_zero() -> sym.Expr: ...
    @staticmethod
    def sym_one() -> sym.Expr: ...
    @staticmethod
    def sym_sin(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_cos(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_tan(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_exp(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_ln(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_sqrt(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_abs(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_diff(expr: sym.Expr, wrt: str, n: int = 1) -> sym.Expr: ...
    @staticmethod
    def sym_integrate(expr: sym.Expr, wrt: str) -> sym.Expr: ...
    @staticmethod
    def sym_definite_integral(expr: sym.Expr, wrt: str, a: float, b: float) -> float: ...
    @staticmethod
    def sym_simplify(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_expand(expr: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_factor(expr: sym.Expr, term: sym.Expr) -> sym.Expr: ...
    @staticmethod
    def sym_solve_linear(expr: sym.Expr, wrt: str) -> sym.Expr: ...
    @staticmethod
    def sym_solve_quadratic(expr: sym.Expr, wrt: str) -> list[sym.Expr]: ...
    @staticmethod
    def sym_taylor(expr: sym.Expr, wrt: str, center: float, n: int) -> sym.Expr: ...
    @staticmethod
    def sym_maclaurin(expr: sym.Expr, wrt: str, n: int) -> sym.Expr: ...


class rl:
    class CartPole:
        def __init__(self) -> None: ...
        def reset(self) -> list[float]: ...
        def step(self, action: int) -> dict[str, Any]: ...
        def observation_shape(self) -> list[int]: ...
        def action_count(self) -> int: ...
        def is_done(self) -> bool: ...

    class MountainCar:
        def __init__(self) -> None: ...
        def reset(self) -> list[float]: ...
        def step(self, action: int) -> dict[str, Any]: ...
        def observation_shape(self) -> list[int]: ...
        def action_count(self) -> int: ...
        def is_done(self) -> bool: ...

    class GridWorld:
        def __init__(self, size: int = 5) -> None: ...
        def reset(self) -> list[float]: ...
        def step(self, action: int) -> dict[str, Any]: ...
        def observation_shape(self) -> list[int]: ...
        def action_count(self) -> int: ...
        def is_done(self) -> bool: ...

    class DQN:
        def __init__(self, input_dim: int, action_count: int, learning_rate: float = 0.001, gamma: float = 0.99, epsilon: float = 1.0, epsilon_decay: float = 0.995, min_epsilon: float = 0.01, batch_size: int = 32, target_update_freq: int = 100, buffer_capacity: int = 10000, seed: int = 42) -> None: ...
        def act(self, observation: list[float]) -> int: ...
        def train_step(self) -> float: ...
        def train_cartpole(self, episodes: int) -> dict[str, Any]: ...
        def train_gridworld(self, size: int, episodes: int) -> dict[str, Any]: ...

    class PPO:
        def __init__(self, input_dim: int, action_count: int, learning_rate: float = 0.0003, gamma: float = 0.99, gae_lambda: float = 0.95, clip_epsilon: float = 0.2, n_epochs: int = 4, n_steps: int = 128, batch_size: int = 32, seed: int = 42) -> None: ...
        def act(self, observation: list[float]) -> tuple[int, float, float]: ...
        def train_cartpole(self, total_timesteps: int) -> dict[str, Any]: ...

    class A2C:
        def __init__(self, input_dim: int, action_count: int, learning_rate: float = 0.0007, gamma: float = 0.99, value_loss_coef: float = 0.5, entropy_coef: float = 0.01, n_steps: int = 5, seed: int = 42) -> None: ...
        def act(self, observation: list[float]) -> tuple[int, float, float]: ...
        def train_cartpole(self, total_timesteps: int) -> dict[str, Any]: ...

    class SAC:
        def __init__(self, state_dim: int, action_dim: int, learning_rate: float = 0.0003, gamma: float = 0.99, tau: float = 0.005, alpha: float = 0.2, batch_size: int = 64, buffer_capacity: int = 10000, seed: int = 42) -> None: ...
        def select_action(self, state: list[float]) -> list[float]: ...
        def train_step(self) -> float: ...
        def state_dim(self) -> int: ...
        def action_dim(self) -> int: ...

    class TD3:
        def __init__(self, state_dim: int, action_dim: int, learning_rate: float = 0.0003, gamma: float = 0.99, tau: float = 0.005, policy_noise: float = 0.2, noise_clip: float = 0.5, policy_delay: int = 2, batch_size: int = 64, buffer_capacity: int = 10000, seed: int = 42) -> None: ...
        def select_action(self, state: list[float], exploration_noise: float = 0.1) -> list[float]: ...
        def train_step(self) -> float: ...
        def state_dim(self) -> int: ...
        def action_dim(self) -> int: ...

    class EpisodeLogger:
        def __init__(self) -> None: ...
        def log_step(self, reward: float) -> None: ...
        def end_episode(self) -> None: ...
        def mean_reward(self, last_n: int) -> float: ...
        def total_episodes(self) -> int: ...
        @property
        def episode_rewards(self) -> list[float]: ...
        @property
        def episode_lengths(self) -> list[int]: ...


class gpu:
    class Device:
        def __init__(self) -> None: ...
        def info(self) -> dict[str, str]: ...

    class GpuTensor:
        def __init__(self, device: gpu.Device, data: list[float], shape: list[int]) -> None: ...
        @staticmethod
        def zeros(device: gpu.Device, shape: list[int]) -> gpu.GpuTensor: ...
        def to_list(self) -> list[float]: ...
        def shape(self) -> list[int]: ...
        def ndim(self) -> int: ...
        def numel(self) -> int: ...

    @staticmethod
    def add(a: gpu.GpuTensor, b: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def sub(a: gpu.GpuTensor, b: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def mul(a: gpu.GpuTensor, b: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def div(a: gpu.GpuTensor, b: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def add_scalar(input: gpu.GpuTensor, scalar: float) -> gpu.GpuTensor: ...
    @staticmethod
    def mul_scalar(input: gpu.GpuTensor, scalar: float) -> gpu.GpuTensor: ...
    @staticmethod
    def sub_scalar(input: gpu.GpuTensor, scalar: float) -> gpu.GpuTensor: ...
    @staticmethod
    def matmul(a: gpu.GpuTensor, b: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def transpose(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def sum(input: gpu.GpuTensor) -> float: ...
    @staticmethod
    def mean(input: gpu.GpuTensor) -> float: ...
    @staticmethod
    def relu(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def sigmoid(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def tanh(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def exp(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def log(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def negate(input: gpu.GpuTensor) -> gpu.GpuTensor: ...
    @staticmethod
    def fill(device: gpu.Device, shape: list[int], value: float) -> gpu.GpuTensor: ...
    @staticmethod
    def detect_backend() -> str: ...


class viz:
    @staticmethod
    def regplot(x: list[float], y: list[float], show_ci: bool = True) -> Figure: ...
    @staticmethod
    def residplot(x: list[float], y: list[float]) -> Figure: ...
    @staticmethod
    def qqplot(data: list[float]) -> Figure: ...
    @staticmethod
    def corrplot(matrix: list[list[float]], labels: list[str] | None = None, show_values: bool = True) -> Figure: ...
